name: quanlyshop
description: "Phần mềm quản lý tiệm sửa chữa mua bán  điện thoại chuyên nghiệp"
publish_to: 'none'
version: 1.0.0+7

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.3.0
  cloud_functions: ^5.3.0
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: 0.20.2
  yaml: ^3.1.2
  image_picker: ^1.0.7
  photo_view: ^0.15.0
  url_launcher: ^6.3.2
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2
  firebase_storage: ^12.4.10
  shared_preferences: ^2.5.4
  screenshot: ^3.0.0
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  gal: ^2.3.2
  mobile_scanner: ^5.1.1
  fl_chart: ^0.66.0
  excel: ^4.0.0
  qr_flutter: ^4.1.0
  permission_handler: ^11.3.1
  flutter_blue_plus: ^1.35.3
  print_bluetooth_thermal: ^1.1.0
  esc_pos_utils: ^1.1.0
  esc_pos_printer: ^4.1.0
  file_picker: ^8.0.0
  connectivity_plus: ^6.0.0
  geolocator: ^12.0.0
  csv: ^6.0.0
  introduction_screen: ^3.1.14
  encrypt: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.11.0
  sqflite_common_ffi: ^2.3.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  generate: true

l10n:
  arb-dir: lib/l10n
  template-arb-file: app_vi.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations
